### ISSUE TITLE
This repository is in direct violation of the GitHub Terms and Services

### ISSUE THREAD

**Issue by Fohlen** [pycaret/pycaret-git-actions#1]
I'm following up from the medium article to this repository. The [GitHub TOS](https://docs.github.com/en/github/site-policy/github-additional-product-terms#a-actions-usage) specifies:

> Actions should not be used for:
> - serverless computing;
> - any other activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used.

Using AutoML is in fact using serverless power to carry out model development. This is **unrelated** to building, testing or deployment of your software in any way. It is also unrelated to production use as PyCaret is **not** used to carry out a specific action that would be needed by other projects to build their software. 

This would be the case if such models would have been previously created, and PyCaret would be used to apply models to a specific problem.

I created this ticket to remind you that GitHub Actions are **not** a hosting platform, and that the maintainers of open source projects depend on computing infrastructure to carry out development. See it as a heads-up instead of directly reporting the repository to GitHub, which **will** delete them, possibly disabling your account in the process.
All the best

**Comment by pycaret** [comment]
@Fohlen Thanks for reporting. We will take appropriate action soon.

**Comment by pycaret** [comment]
@Fohlen Thanks for reporting.

Thank you Lennard for reporting this. We take compliance to GitHub Actions TOS very seriously and have as such edited the story and included disclosure. I have also changed the title image. We will also send a disclosure on our social media handle today mentioning that it is against GitHub ToS to use it as a serverless compute for hosting.

Unfortunately title cannot be edited and it wouldn't be fair to recall the story.

Appreciate your support.

Thank you.

**Comment by AnimMouse** [comment]
Not anymore.
[Run your ML workloads on GitHub Actions with GPU runners](https://github.blog/changelog/2023-10-31-run-your-ml-workloads-on-github-actions-with-gpu-runners/)
